//
// Generated file, do not edit! Created by nedtool 5.5 from veins/modules/application/traci/CHAMessage.msg.
//

#ifndef __VEINS_CHAMESSAGE_M_H
#define __VEINS_CHAMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/CHAMessage.msg:31</tt> by nedtool.
 * <pre>
 * packet CHAMessage extends BaseFrame1609_4
 * {
 *     LAddress::L2Type senderAddress = -1;
 *     Coord curPosition;
 *     Coord curSpeed;
 *     int SNNum;
 * }
 * </pre>
 */
class VEINS_API CHAMessage : public ::veins::BaseFrame1609_4
{
  protected:
    LAddress::L2Type senderAddress;
    Coord curPosition;
    Coord curSpeed;
    int SNNum;

  private:
    void copy(const CHAMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CHAMessage&);

  public:
    CHAMessage(const char *name=nullptr, short kind=0);
    CHAMessage(const CHAMessage& other);
    virtual ~CHAMessage();
    CHAMessage& operator=(const CHAMessage& other);
    virtual CHAMessage *dup() const override {return new CHAMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual LAddress::L2Type& getSenderAddress();
    virtual const LAddress::L2Type& getSenderAddress() const {return const_cast<CHAMessage*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
    virtual Coord& getCurPosition();
    virtual const Coord& getCurPosition() const {return const_cast<CHAMessage*>(this)->getCurPosition();}
    virtual void setCurPosition(const Coord& curPosition);
    virtual Coord& getCurSpeed();
    virtual const Coord& getCurSpeed() const {return const_cast<CHAMessage*>(this)->getCurSpeed();}
    virtual void setCurSpeed(const Coord& curSpeed);
    virtual int getSNNum() const;
    virtual void setSNNum(int SNNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CHAMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CHAMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_CHAMESSAGE_M_H

