//
// Generated file, do not edit! Created by nedtool 5.5 from veins/modules/application/ieee80211p/CHABoardcastMessage.msg.
//

#ifndef __VEINS_CHABOARDCASTMESSAGE_M_H
#define __VEINS_CHABOARDCASTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/modules/messages/DemoSafetyMessage_m.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/ieee80211p/CHABoardcastMessage.msg:27</tt> by nedtool.
 * <pre>
 * packet CHABoardcastMessage extends DemoSafetyMessage
 * {
 *     int SNNum;
 * }
 * </pre>
 */
class VEINS_API CHABoardcastMessage : public ::veins::DemoSafetyMessage
{
  protected:
    int SNNum;

  private:
    void copy(const CHABoardcastMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CHABoardcastMessage&);

  public:
    CHABoardcastMessage(const char *name=nullptr, short kind=0);
    CHABoardcastMessage(const CHABoardcastMessage& other);
    virtual ~CHABoardcastMessage();
    CHABoardcastMessage& operator=(const CHABoardcastMessage& other);
    virtual CHABoardcastMessage *dup() const override {return new CHABoardcastMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSNNum() const;
    virtual void setSNNum(int SNNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CHABoardcastMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CHABoardcastMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_CHABOARDCASTMESSAGE_M_H

