//
// Generated file, do not edit! Created by nedtool 5.5 from veins/modules/application/ieee80211p/ReqJoinMessage.msg.
//

#ifndef __VEINS_REQJOINMESSAGE_M_H
#define __VEINS_REQJOINMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/modules/messages/DemoSafetyMessage_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/ieee80211p/ReqJoinMessage.msg:28</tt> by nedtool.
 * <pre>
 * packet ReqJoinMessage extends DemoSafetyMessage
 * {
 * }
 * </pre>
 */
class VEINS_API ReqJoinMessage : public ::veins::DemoSafetyMessage
{
  protected:

  private:
    void copy(const ReqJoinMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReqJoinMessage&);

  public:
    ReqJoinMessage(const char *name=nullptr, short kind=0);
    ReqJoinMessage(const ReqJoinMessage& other);
    virtual ~ReqJoinMessage();
    ReqJoinMessage& operator=(const ReqJoinMessage& other);
    virtual ReqJoinMessage *dup() const override {return new ReqJoinMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReqJoinMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReqJoinMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_REQJOINMESSAGE_M_H

